services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file: 
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"

  bot:
    build: .
    command: sh -c "python -m main"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
    volumes:
      - ./database/db.sqlite3:/app/database/db.sqlite3
