version: '3.8'

services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file: 
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"

  postgres:
    image: postgres: 13
    restart: always
    environment:
      POSTGRES_USER: remez
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    command: sh -c "python -m main"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - postgres
